UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = '101OBEX, CORP';
UPDATE underlying_portfolio_holdings SET type = 'Deep Tech, Tech Based' WHERE company_name = 'Earth AI, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'BRK Health Solutions';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Liitto Technology, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Rainmaker Technology Corporation';
UPDATE underlying_portfolio_holdings SET type = 'Deep Tech, Tech Based' WHERE company_name = 'Blue Energy Global Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Earth Force Technologies, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Earthmover PBC';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Storio Energy';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Near Space Labs, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'CargoKite GmbH';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Urban Agrotech B.V.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Airloom Energy, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Airtonomy Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Air Company Holdings, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Deep Tech, Tech Based' WHERE company_name = 'Andean Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Beam Tech Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Boombox Interactive, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Deep Tech, Tech Based' WHERE company_name = 'Chaos Industries, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Checksum AI, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Deep Tech, Tech Based' WHERE company_name = 'Coronal Technologies, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Delineate Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Emerald AI, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Firedomer Ltd';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Fly Media, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based, Tech Enabled' WHERE company_name = 'Fonda Technologies Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Deep Tech, Tech Based' WHERE company_name = 'Framework Automation Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Genvision Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Hedral, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Jarwin, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Leal Holdings, Ltd';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Loamist, Co.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Longview Restoration Group, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Lumora Technologies';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Mammoth Climate PBC';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'NIC Corporate Fund LP';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based, Tech Enabled' WHERE company_name = 'OhmEV, LLC';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Phosphor Co.';
UPDATE underlying_portfolio_holdings SET type = 'Deep Tech, Tech Based' WHERE company_name = 'Place Genomics Corporation';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Reload PL, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Renewell Energy Inc';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'ReynKo, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Rilian Technologies, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Swell Cycle Surfboards';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Terminal Station Holdings, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Thalo Labs, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'The New Industrial Corporation';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Velma Energy Company';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Vevo Therapeutics Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Voidr Holdings Limited';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Wild Technologies, Inc';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Wonderfil PBC';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Zoo Corporation';
UPDATE underlying_portfolio_holdings SET type = 'Deep Tech, Tech Based' WHERE company_name = 'Everstar, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Leap-Transform Finix Opportunity SPV, LP';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Energy Applied, Inc.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Around Corp.';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Momentum Climate PBC';
UPDATE underlying_portfolio_holdings SET type = 'Tech Based' WHERE company_name = 'Streamline Climate, Inc.';